

export const gameItems = [
  { name: "stone", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft/images/d/d4/Stone.png/revision/latest?cb=20200825201332" },
  { name: "dirt", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/2f/Dirt.png/revision/latest/scale-to-width-down/300?cb=20220112085643" },
  { name: "golden_apple", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/54/Golden_Apple_JE2_BE2.png/revision/latest?cb=20200521041809" },
  { name: "diamond_sword", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/44/Diamond_Sword_JE3_BE3.png/revision/latest/scale-to-width-down/160?cb=20201017135722" },
  { name: "diamond_pickaxe", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e7/Diamond_Pickaxe_JE3_BE3.png/revision/latest/scale-to-width-down/160?cb=20200226193952" },
  { name: "diamond_axe", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/Diamond_Axe_JE3_BE3.png/revision/latest?cb=20200226193844" },
  { name: "diamond_hoe", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/04/Diamond_Hoe_JE3_BE3.png/revision/latest/scale-to-width-down/160?cb=20200226193929" },
  { name: "diamond_shovel", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/ec/Diamond_Shovel_JE3_BE3.png/revision/latest/scale-to-width-down/160?cb=20200226194003" },
  { name: "diamond", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/ab/Diamond_JE3_BE3.png/revision/latest/scale-to-width-down/160?cb=20200325185152" },
  { name: "gold", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8a/Gold_Ingot_JE4_BE2.png/revision/latest/scale-to-width-down/160?cb=20200224211607" },
  { name: "obsidian", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/99/Obsidian_JE3_BE2.png/revision/latest?cb=20200124042057" },
  { name: "ender_pearl", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f6/Ender_Pearl_JE3_BE2.png/revision/latest/scale-to-width-down/1200?cb=20200512195721" },
  { name: "leather", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/6d/Leather_JE2_BE2.png/revision/latest?cb=20190430052953" },
  { name: "carrot", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft/images/6/63/Carrot_Updated.png/revision/latest?cb=20190721134506" },
  { name: "apple", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/af/Apple_JE3_BE3.png/revision/latest?cb=20200519232834" },
  { name: "bone", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/3a/Bone_JE3_BE2.png/revision/latest/scale-to-width-down/160?cb=20190501043304" },
  { name: "rotten_flesh", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/ac/Rotten_Flesh_JE3_BE2.png/revision/latest/scale-to-width-down/160?cb=20190521031955" },
  { name: "gun_powder", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/Gunpowder_JE2_BE2.png/revision/latest?cb=20190816222615" },
  { name: "bow", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/99/Bow_JE2_BE1.png/revision/latest/scale-to-width-down/160?cb=20200128015144" },
  { name: "bucket", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/fc/Bucket_JE2_BE2.png/revision/latest/scale-to-width-down/160?cb=20200510234539" },
  { name: "egg", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/96/Egg_JE2_BE2.png/revision/latest?cb=20200512195802" },
  { name: "saddle", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/ba/Saddle_JE2_BE2.png/revision/latest/scale-to-width-down/160?cb=20190531030308" },
  { name: "emerald", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/26/Emerald_JE3_BE3.png/revision/latest/scale-to-width-down/160?cb=20191229174220" },
  { name: "redstone", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d5/Redstone_Dust_JE1_BE1.png/revision/latest/scale-to-width-down/160?cb=20200128033435" },
  { name: "lapis", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/43/Lapis_Lazuli_JE2_BE2.png/revision/latest?cb=20190430045315" },
  { name: "piston", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/2d/Piston_%28U%29_JE1.png/revision/latest/scale-to-width-down/300?cb=20201119122514" },
  { name: "iron", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/fc/Iron_Ingot_JE3_BE2.png/revision/latest/scale-to-width-down/160?cb=20200523233216" },
  { name: "diamond_helmet", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/73/Diamond_Helmet_%28item%29_JE1_BE1.png/revision/latest/scale-to-width-down/160?cb=20190403172039" },
  { name: "diamond_chestplate", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e3/Diamond_Chestplate_%28item%29_JE1_BE1.png/revision/latest/scale-to-width-down/160?cb=20190403171906" },
  { name: "diamond_leggings", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8e/Diamond_Leggings_%28item%29_JE1_BE1.png/revision/latest/scale-to-width-down/160?cb=20190403172133" },
  { name: "diamond_boots", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f0/Diamond_Boots_%28item%29_JE1_BE1.png/revision/latest/scale-to-width-down/160?cb=20190403171843" },
  { name: "tnt", isSelected: false, isMatched: false, image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a2/TNT_JE3_BE2.png/revision/latest/scale-to-width-down/300?cb=20210110120939" },
];
